### ISSUE TITLE
Unable to launch mDeepFRI

### ISSUE THREAD

**Issue by annotatebio** [bioinf-mcb/Metagenomic-DeepFRI#84]
Hi All,

I've been trying to take mDeepFRI for a spin but I'm facing issues early on: while trying to run `--help` flag, I get a following error:

```bash
mDeepFRI --help

Traceback (most recent call last):
  File "/home/oem/miniconda3/envs/deepfri/bin/mDeepFRI", line 33, in <module>
    sys.exit(load_entry_point('mDeepFRI==1.1.6', 'console_scripts', 'mDeepFRI')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/deepfri/bin/mDeepFRI", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/deepfri/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/deepfri/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/oem/bioinformatics-tools/Metagenomic-DeepFRI/Metagenomic-DeepFRI/mDeepFRI/cli.py", line 11, in <module>
    from mDeepFRI.pipeline import (hierarchical_database_search,
  File "/home/oem/bioinformatics-tools/Metagenomic-DeepFRI/Metagenomic-DeepFRI/mDeepFRI/pipeline.py", line 14, in <module>
    from mDeepFRI.bio_utils import build_align_contact_map
  File "/home/oem/bioinformatics-tools/Metagenomic-DeepFRI/Metagenomic-DeepFRI/mDeepFRI/bio_utils.py", line 14, in <module>
    from mDeepFRI.alignment_utils import align_contact_map, pairwise_sqeuclidean
ModuleNotFoundError: No module named 'mDeepFRI.alignment_utils'
```

Indeed I do not see `alignment_utils` anywhere - I either see `alignment` module or `bio_utils`.

```bash
ll mDeepFRI
total 2696
drwxrwxr-x  4 oem oem    4096 cze  6 16:30 ./
drwxrwxr-x 11 oem oem    4096 cze  6 16:31 ../
-rw-rw-r--  1 oem oem    7706 cze  6 16:27 alignment.py
-rw-rw-r--  1 oem oem    9432 cze  6 16:27 bio_utils.py
-rw-rw-r--  1 oem oem   12613 cze  6 16:27 cli.py
-rw-rw-r--  1 oem oem 1196132 cze  6 16:30 contact_map_utils.cpp
-rw-rw-r--  1 oem oem    6421 cze  6 16:27 contact_map_utils.pyx
-rw-rw-r--  1 oem oem    3095 cze  6 16:27 database.py
-rw-rw-r--  1 oem oem    4194 cze  6 16:27 __init__.py
-rw-rw-r--  1 oem oem   21704 cze  6 16:27 mmseqs.py
-rw-rw-r--  1 oem oem    4591 cze  6 16:27 pdb.py
-rw-rw-r--  1 oem oem   13870 cze  6 16:27 pipeline.py
-rw-rw-r--  1 oem oem 1420033 cze  6 16:30 predict.cpp
-rw-rw-r--  1 oem oem    4379 cze  6 16:27 predict.pyx
drwxrwxr-x  2 oem oem    4096 cze  6 16:27 __pycache__/
drwxrwxr-x  3 oem oem    4096 cze  6 16:27 tests/
-rw-rw-r--  1 oem oem    7834 cze  6 16:27 utils.py
```

Is the repository up to date, or are you in the middle of some changes/development?

Thanks in advance :)

**Comment by tkosciol** [comment]
@valentynbez could you take a look at this whenever available?
@lmszydlowski is this something that you ran into?

**Comment by valentynbez** [comment]
Hello @annotatebio! 

Indeed, it is connected to the fact that the functionality of this module was completely put to [Pyopal](https://github.com/althonos/pyopal). However, legacy compiled modules were still present locally, therefore no error was observed. 
This should be fixed already, please try reinstalling the software. Sorry for the inconvenience!

**Comment by annotatebio** [comment]
Thanks for the quick reaction :) Looks like one layer of the issue got resolved, but we still have some leftovers to fix?

```bash
mDeepFRI --help
Traceback (most recent call last):
  File "/home/oem/miniconda3/envs/deepfri/bin/mDeepFRI", line 33, in <module>
    sys.exit(load_entry_point('mDeepFRI==1.1.7', 'console_scripts', 'mDeepFRI')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/deepfri/bin/mDeepFRI", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/deepfri/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/deepfri/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/oem/bioinformatics-tools/Metagenomic-DeepFRI/Metagenomic-DeepFRI/mDeepFRI/cli.py", line 11, in <module>
    from mDeepFRI.pipeline import (hierarchical_database_search,
  File "/home/oem/bioinformatics-tools/Metagenomic-DeepFRI/Metagenomic-DeepFRI/mDeepFRI/pipeline.py", line 14, in <module>
    from mDeepFRI.bio_utils import build_align_contact_map
  File "/home/oem/bioinformatics-tools/Metagenomic-DeepFRI/Metagenomic-DeepFRI/mDeepFRI/bio_utils.py", line 14, in <module>
    from mDeepFRI.contact_map_utils import align_contact_map, pairwise_sqeuclidean
ModuleNotFoundError: No module named 'mDeepFRI.contact_map_utils'
```

**Comment by valentynbez** [comment]
Hi, 
yesterday CI/CD run failed due to reasons not clear to me. 
Could you run `pip install mdeepfri --force-reinstall`? It should resolve the issue.

**Comment by annotatebio** [comment]
Success! (At least with running `mDeepFRI --help`. Thanks for the help :)

**Comment by valentynbez** [comment]
To avoid such problems in the future I implemented full CI/CD pipeline and unit tests https://github.com/bioinf-mcb/Metagenomic-DeepFRI/commit/dca6ce78dd4d7b02518538bfd6a3239d2527aea7. 
Now you can install `mDeepFRI` straight from PyPI, although installation takes a few minutes. 
Thanks for reporting the issue @annotatebio!

**Comment by annotatebio** [comment]
That sounds like a solid solution! Thanks for swift reaction @valentynbez :)

**Comment by valentynbez** [comment]
@annotatebio we are collecting information about use-cases of DeepFRI. In case you're willing to share and discuss your problem, don't hesitate to reach out.
We'd like to accumulate examples in documentation, making it more robust based on users' requirements :)
